services:
  accounts:
    image: "hendrowunga073884/accounts:accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hendrowunga073884
  loans:
    image: "hendrowunga073884/loans:loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hendrowunga073884
  cards:
    image: "hendrowunga073884/cards:cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hendrowunga073884
networks:
  hendrowunga073884:
    driver: "bridge"